#!/usr/bin/env python

import sys
import argparse

HELP = '''Print selected parts of lines from each FILE to standard output.
With no FILE, or when FILE is -, read standard input.'''

class lib(object):
    open = open
    stdin = sys.stdin

parser = argparse.ArgumentParser(description=HELP)
parser.add_argument('-d', dest='delim', default='\t',
                    help='use DELIM instead of TAB for field delimiter')
parser.add_argument('-f', dest='fields',
                    help='select only these fields; also print any line that contains no delimiter character, unless the -s option is specified')
parser.add_argument('-b', dest='bytes',
                    help='select only these bytes')
parser.add_argument('-c', dest='characters',
                    help='select only these characters')
parser.add_argument('-n', dest='ignored', action='store_const', const=None, default=None,
                    help='(ignored)')
parser.add_argument('--output-delimiter', dest='STRING',
                    help='use  STRING  as  the output delimiter the default is to use the input delimiter')
parser.add_argument('file', nargs='?',
                    help='FILE')


def arg_split(s):
    return [int(field)-1 for field in s.split(',')]


def fields_op(line):
    line = line.split(args.delim)
    for field in args.fields:
        try:
            result = line[field]
        except IndexError:
            pass
        else:
            result = result.strip('\n')
            result += args.out_delim
            yield result


def characters_op(line):
    line = list(line)
    for char in args.bytes:
        try:
            result = line[char]
        except IndexError:
            pass
        else:
            result += args.out_delim
            yield result


args = parser.parse_args()
args.out_delim = args.STRING
if args.fields is not None:
    args.fields = arg_split(args.fields)
    if args.out_delim is None:
        args.out_delim = args.delim
    main_op = fields_op
elif args.bytes is not None:
    args.bytes = arg_split(args.bytes)
    if args.out_delim is None:
        args.out_delim = ''
    main_op = characters_op
elif args.characters is not None:
    args.characters = arg_split(args.characters)
    if args.out_delim is None:
        args.out_delim = ''
    main_op = characters_op
else:
    sys.stderr.write("%s: you must specify a list of bytes, characters, or fields. Try '--help' for more information.\n" % sys.argv[0])
    exit(1)


def main_loop(fd):
    for line in fd:
        for result in main_op(line):
            sys.stdout.write(result)
        sys.stdout.write('\n')


if args.file is None:
    main_loop(lib.stdin)
else:
    with lib.open(args.file) as f:
        main_loop(f)
